### ISSUE TITLE
errors cloning

### ISSUE THREAD

**Issue by juanmendez** [jpotts18/android-mvp#1]
hi, I watched your youtube video and I really liked it so I try to clone the project you made available. I just wanted to let you know that for cloning the instruction you wrote gave me an error 

Cloning into 'android-mvp'...
Warning: Permanently added the RSA host key for IP address '19x.xx.xxx.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I used instead
git clone https://github.com/jpotts18/android-mvp

and it worked.

**Comment by philipbrito** [comment]
@juanmendez Did you try to clone this project from command line? If yes, maybe you should use the sudo before git clone command.

`
 sudo git clone git@github.com:jpotts18/android-mvp.git
`

**Comment by jpotts18** [comment]
Since this is a computer configuration problem not a problem with my library I will be closing this issue.
