### ISSUE TITLE
Getting rest adapter from interactor

### ISSUE THREAD

**Issue by EfeBudak** [jpotts18/android-mvp#11]
I have implemented your example and tried to integrate dagger2 example from https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger-2 .

However, I couldn't find a way to get "netComponent", which was build on Application class, from interactor class. 
My main intention is to use retrofit object in "interactor" class. Should I pass it as a parameter or is there a more elegant way?

**Comment by RajuSE** [comment]
@EfeBudak hope [this](https://github.com/RajuSE/CodeDagger2/blob/master/app/src/main/java/rajusugale/dev/dagger2/di/components/HttpComponent.java) helps..
