### ISSUE TITLE
Upgrade current Retrofit to v2

### ISSUE THREAD

**Issue by RajuSE** [jpotts18/android-mvp#17]
@jpotts18 
Thanks for nice brief on MVP. This has been a topic to discuss for last 2 years.

Well, Project has Retrofit1.9 related sphagetti code, So I have made  [pull#18](https://github.com/jpotts18/android-mvp/pull/18) for upgradation Retrofit to v**2.0.2** which is **stable**. Due to this, there will lot of code changes are required which I have covered and tested. Everything works fine.
I've also added diagram in Wiki to simplify understanding: https://github.com/jpotts18/android-mvp/wiki/Diagramatic-representation
Just thought I'd raise a quick question to get your thoughts.

Thanks,

**Comment by jpotts18** [comment]
Can this be closed now?
