### ISSUE TITLE
Incorrect edittext ids

### ISSUE THREAD

**Issue by RajuSE** [jpotts18/android-mvp#19]
While making changes I found incorrect edittext ids.. so I have fixed that as in:
https://github.com/jpotts18/android-mvp/pull/18/commits/0c75ef47571ada4350f8002d4ec035de5912411e

**Comment by jpotts18** [comment]
Resolved?

**Comment by RajuSE** [comment]
It has been fixed in` master-2`, but `master` doesn't have the missing line, hence build fails.
Fixed in #21.
