### ISSUE TITLE
Missing retrofit dependency

### ISSUE THREAD

**Issue by RajuSE** [jpotts18/android-mvp#20]
While making changes I found missing retrofit dependency.. so I fixed as in :
github.com/jpotts18/android-mvp/pull/18/commits/9d131ce4c7b776ffe737bab2c61d21f539610ddb

**Comment by jpotts18** [comment]
I hope this is resolved in `master-2`

**Comment by RajuSE** [comment]
It has been fixed in `master-2`, but `master ` doesn't have the missing line, hence build fails.
Fixed in https://github.com/jpotts18/android-mvp/pull/21.
