### ISSUE TITLE
[request] can you go a little further with Rx implementation without dagger

### ISSUE THREAD

**Issue by rinav** [jpotts18/android-mvp#8]
Recently I started reading a lot about MVP and I want to get into practicing my projects with it. 

However I am not able to correctly understand where should Rx + Retrofit code go? I think it should be in Model Layer via Interactors but still can you help me understand?

Also what happens with the RX callback? the onNext(), onCompleted() and onFailure() passes data back to Presenter or do we implement listeners? Also should we decouple Rx callbacks further?

**Comment by jpotts18** [comment]
I don't know enough about Rx, so unfortunately no.

**Comment by RajuSE** [comment]
@riinav chekout https://github.com/jpotts18/android-mvp/tree/master-2
